"preserve_hierarchy": true

files: [
  {
    "source": "/EFBChannels/efb-fb-messenger-slave/efb_fb_messenger_slave/locale/*.pot",
    "translation": "/EFBChannels/efb-fb-messenger-slave/efb_fb_messenger_slave/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po",
  },
  {
    "source": "/EFBChannels/efb-fb-messenger-slave/readme_translations/locale/README.pot",
    "translation": "/EFBChannels/efb-fb-messenger-slave/readme_translations/locale/%locale_with_underscore%.po"
  }
]